// Generated by apigen cli from backend/openapi.json — do not edit by hand.
// Every feature route as `api <area> <action>`; the call goes through callRoute
// (cli/src/lib/apigen-call.ts), which uses this CLI's own sign-in and client, and bad
// input through failRoute (the CLI's own error output).
import { Command } from 'commander';
import { callRoute, failRoute } from '../lib/apigen-call.js';

type Kind = 'string' | 'number' | 'boolean' | 'array' | 'json';
interface Field { name: string; kind: Kind; required: boolean; choices?: string[] }
interface Route { name: string; aliases?: string[]; method: string; path: string; summary: string; pathParams: string[]; query: Field[]; body: Field[] | null }

export const API_ROUTES: Array<{ area: string; routes: Route[] }> = [
 {
  "area": "account",
  "routes": [
   {
    "name": "audit",
    "method": "GET",
    "path": "/api/v1/account/audit",
    "summary": "List audit",
    "pathParams": [],
    "query": [
     {
      "name": "limit",
      "kind": "number",
      "required": false
     },
     {
      "name": "cursor",
      "kind": "string",
      "required": false
     },
     {
      "name": "event",
      "kind": "string",
      "required": false
     },
     {
      "name": "outcome",
      "kind": "string",
      "required": false,
      "choices": [
       "success",
       "failure",
       "denied"
      ]
     },
     {
      "name": "since",
      "kind": "string",
      "required": false
     },
     {
      "name": "until",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "billing",
    "method": "GET",
    "path": "/api/v1/account/billing",
    "summary": "/billing surface for the Huudis dashboard.",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "billing-cancel",
    "method": "POST",
    "path": "/api/v1/account/billing/cancel",
    "summary": "Create a cancel",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "billing-checkout",
    "method": "POST",
    "path": "/api/v1/account/billing/checkout",
    "summary": "Create a checkout",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "tier",
      "kind": "string",
      "required": true,
      "choices": [
       "pro",
       "business",
       "scale"
      ]
     }
    ]
   },
   {
    "name": "billing-invoices",
    "method": "GET",
    "path": "/api/v1/account/billing/invoices",
    "summary": "List invoices",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "billing-plans",
    "method": "GET",
    "path": "/api/v1/account/billing/plans",
    "summary": "Public to authenticated sessions — no account scope needed since every user sees the same plans.",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "billing-usage",
    "method": "GET",
    "path": "/api/v1/account/billing/usage",
    "summary": "List usage",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "cancel-deletion",
    "method": "POST",
    "path": "/api/v1/account/cancel-deletion",
    "summary": "Create a cancel deletion",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "connected-apps",
    "method": "GET",
    "path": "/api/v1/account/connected-apps",
    "summary": "Signal = `RefreshToken`, not `OidcConsent`.",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "connected-apps-revoke",
    "method": "POST",
    "path": "/api/v1/account/connected-apps/{clientId}/revoke",
    "summary": "Revoke every live refresh-token family this user holds for the client.",
    "pathParams": [
     "clientId"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "create-webhook-subscriptions",
    "method": "POST",
    "path": "/api/v1/account/webhook-subscriptions",
    "summary": "Create a webhook subscription",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "url",
      "kind": "string",
      "required": true
     },
     {
      "name": "events",
      "kind": "array",
      "required": true
     },
     {
      "name": "description",
      "kind": "string",
      "required": false
     },
     {
      "name": "active",
      "kind": "boolean",
      "required": false
     }
    ]
   },
   {
    "name": "create-workspaces",
    "method": "POST",
    "path": "/api/v1/account/workspaces",
    "summary": "Create a workspace",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": true
     }
    ]
   },
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/account",
    "summary": "Delete account",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "password",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "delete-connected-apps",
    "method": "DELETE",
    "path": "/api/v1/account/connected-apps/{id}",
    "summary": "Legacy consent-id path.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "delete-linked-accounts",
    "method": "DELETE",
    "path": "/api/v1/account/linked-accounts/{provider}",
    "summary": "Delete a linked account",
    "pathParams": [
     "provider"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "delete-social-providers",
    "method": "DELETE",
    "path": "/api/v1/account/social-providers/{provider}",
    "summary": "Delete a social provider",
    "pathParams": [
     "provider"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "delete-webhook-subscriptions",
    "method": "DELETE",
    "path": "/api/v1/account/webhook-subscriptions/{id}",
    "summary": "Delete a webhook subscription",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "email-change",
    "method": "POST",
    "path": "/api/v1/account/email-change",
    "summary": "Create an email change",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "email",
      "kind": "string",
      "required": true
     },
     {
      "name": "password",
      "kind": "string",
      "required": true
     }
    ]
   },
   {
    "name": "get-webhook-subscriptions",
    "method": "GET",
    "path": "/api/v1/account/webhook-subscriptions/{id}",
    "summary": "Get a webhook subscription",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null,
    "aliases": [
     "webhook-subscriptions-2"
    ]
   },
   {
    "name": "linked-accounts",
    "method": "GET",
    "path": "/api/v1/account/linked-accounts",
    "summary": "List linked accounts",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/account",
    "summary": "List account",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "password-change",
    "method": "POST",
    "path": "/api/v1/account/password-change",
    "summary": "Create a password change",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "currentPassword",
      "kind": "string",
      "required": false
     },
     {
      "name": "newPassword",
      "kind": "string",
      "required": true
     }
    ]
   },
   {
    "name": "schedule-deletion",
    "method": "POST",
    "path": "/api/v1/account/schedule-deletion",
    "summary": "Self-serve soft-delete: stamps a 30-day grace marker.",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "password",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "services",
    "method": "GET",
    "path": "/api/v1/account/services",
    "summary": "List services",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "services-disable",
    "method": "POST",
    "path": "/api/v1/account/services/disable",
    "summary": "Create a disable",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "services",
      "kind": "array",
      "required": true
     }
    ]
   },
   {
    "name": "services-enable",
    "method": "POST",
    "path": "/api/v1/account/services/enable",
    "summary": "Create an enable",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "services",
      "kind": "array",
      "required": true
     }
    ]
   },
   {
    "name": "sessions",
    "method": "GET",
    "path": "/api/v1/account/sessions",
    "summary": "List sessions",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "sessions-revoke",
    "method": "POST",
    "path": "/api/v1/account/sessions/{id}/revoke",
    "summary": "Revoke a session",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "sessions-revoke-all",
    "method": "POST",
    "path": "/api/v1/account/sessions/revoke-all",
    "summary": "Create a revoke all",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "set-social-providers",
    "method": "PUT",
    "path": "/api/v1/account/social-providers/{provider}",
    "summary": "Replace a social provider",
    "pathParams": [
     "provider"
    ],
    "query": [],
    "body": [
     {
      "name": "clientId",
      "kind": "string",
      "required": true
     },
     {
      "name": "secret",
      "kind": "string",
      "required": false
     },
     {
      "name": "redirectUri",
      "kind": "string",
      "required": false
     },
     {
      "name": "teamId",
      "kind": "string",
      "required": false
     },
     {
      "name": "keyId",
      "kind": "string",
      "required": false
     },
     {
      "name": "enabled",
      "kind": "boolean",
      "required": false
     }
    ]
   },
   {
    "name": "social-providers",
    "method": "GET",
    "path": "/api/v1/account/social-providers",
    "summary": "List social providers",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "update",
    "method": "PATCH",
    "path": "/api/v1/account",
    "summary": "Update account",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": false
     },
     {
      "name": "locale",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "update-webhook-subscriptions",
    "method": "PATCH",
    "path": "/api/v1/account/webhook-subscriptions/{id}",
    "summary": "Update a webhook subscription",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "url",
      "kind": "string",
      "required": false
     },
     {
      "name": "events",
      "kind": "array",
      "required": false
     },
     {
      "name": "description",
      "kind": "string",
      "required": false
     },
     {
      "name": "active",
      "kind": "boolean",
      "required": false
     }
    ]
   },
   {
    "name": "update-workspaces",
    "method": "PATCH",
    "path": "/api/v1/account/workspaces/{id}",
    "summary": "Update a workspace",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": true
     }
    ]
   },
   {
    "name": "webhook-subscriptions",
    "method": "GET",
    "path": "/api/v1/account/webhook-subscriptions",
    "summary": "List webhook subscriptions",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "webhook-subscriptions-deliveries",
    "method": "GET",
    "path": "/api/v1/account/webhook-subscriptions/{id}/deliveries",
    "summary": "List deliveries",
    "pathParams": [
     "id"
    ],
    "query": [
     {
      "name": "limit",
      "kind": "string",
      "required": false
     },
     {
      "name": "status",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "webhook-subscriptions-deliveries-replay",
    "method": "POST",
    "path": "/api/v1/account/webhook-subscriptions/deliveries/{id}/replay",
    "summary": "Replay a delivery",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "webhook-subscriptions-events-catalog",
    "method": "GET",
    "path": "/api/v1/account/webhook-subscriptions/events/catalog",
    "summary": "List catalog",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "webhook-subscriptions-rotate-secret",
    "method": "POST",
    "path": "/api/v1/account/webhook-subscriptions/{id}/rotate-secret",
    "summary": "Rotate secret a webhook subscription",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "workspaces",
    "method": "GET",
    "path": "/api/v1/account/workspaces",
    "summary": "List workspaces",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "workspaces-cancel-deletion",
    "method": "POST",
    "path": "/api/v1/account/workspaces/{id}/cancel-deletion",
    "summary": "Cancel deletion a workspace",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "workspaces-members",
    "method": "GET",
    "path": "/api/v1/account/workspaces/{id}/members",
    "summary": "Additive, read-only.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "workspaces-schedule-deletion",
    "method": "POST",
    "path": "/api/v1/account/workspaces/{id}/schedule-deletion",
    "summary": "Owner-only soft-delete: stamps a 30-day grace marker on the workspace.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "workspaces-switch",
    "method": "POST",
    "path": "/api/v1/account/workspaces/{id}/switch",
    "summary": "Switch a workspace",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "app",
  "routes": [
   {
    "name": "overview",
    "method": "GET",
    "path": "/api/v1/app/overview",
    "summary": "One row per OIDC client that has ever minted a refresh token: distinct users, 30-day signups, last signup + last activity.",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "stats",
    "method": "GET",
    "path": "/api/v1/app/stats",
    "summary": "List stats",
    "pathParams": [],
    "query": [
     {
      "name": "q",
      "kind": "string",
      "required": false
     },
     {
      "name": "status",
      "kind": "string",
      "required": false,
      "choices": [
       "all",
       "active",
       "disabled"
      ]
     },
     {
      "name": "limit",
      "kind": "number",
      "required": false
     },
     {
      "name": "clientId",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "users",
    "method": "GET",
    "path": "/api/v1/app/users",
    "summary": "List users",
    "pathParams": [],
    "query": [
     {
      "name": "q",
      "kind": "string",
      "required": false
     },
     {
      "name": "status",
      "kind": "string",
      "required": false,
      "choices": [
       "all",
       "active",
       "disabled"
      ]
     },
     {
      "name": "limit",
      "kind": "number",
      "required": false
     },
     {
      "name": "clientId",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "workspaces",
    "method": "GET",
    "path": "/api/v1/app/workspaces",
    "summary": "List workspaces",
    "pathParams": [],
    "query": [
     {
      "name": "ids",
      "kind": "string",
      "required": true
     }
    ],
    "body": null
   }
  ]
 },
 {
  "area": "authz",
  "routes": [
   {
    "name": "assume-role",
    "method": "POST",
    "path": "/api/v1/authz/assume-role",
    "summary": "Create an assume role",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "roleId",
      "kind": "string",
      "required": true
     },
     {
      "name": "sessionName",
      "kind": "string",
      "required": false
     },
     {
      "name": "durationSeconds",
      "kind": "number",
      "required": false
     }
    ]
   },
   {
    "name": "check",
    "method": "POST",
    "path": "/api/v1/authz/check",
    "summary": "Create a check",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "principal",
      "kind": "json",
      "required": true
     },
     {
      "name": "action",
      "kind": "string",
      "required": true
     },
     {
      "name": "resource",
      "kind": "string",
      "required": true
     },
     {
      "name": "context",
      "kind": "json",
      "required": false
     }
    ]
   },
   {
    "name": "whoami",
    "method": "GET",
    "path": "/api/v1/authz/whoami",
    "summary": "Session-auth health ping so dashboard can verify reachability.",
    "pathParams": [],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "iam",
  "routes": [
   {
    "name": "access-keys",
    "method": "GET",
    "path": "/api/v1/iam/access-keys",
    "summary": "List access keys",
    "pathParams": [],
    "query": [
     {
      "name": "principalType",
      "kind": "string",
      "required": true,
      "choices": [
       "user",
       "service_account"
      ]
     },
     {
      "name": "principalId",
      "kind": "string",
      "required": true
     }
    ],
    "body": null
   },
   {
    "name": "access-keys-revoke",
    "method": "POST",
    "path": "/api/v1/iam/access-keys/{id}/revoke",
    "summary": "Revoke an access key",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "assumed-sessions",
    "method": "GET",
    "path": "/api/v1/iam/assumed-sessions",
    "summary": "List assumed sessions",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "assumed-sessions-revoke",
    "method": "POST",
    "path": "/api/v1/iam/assumed-sessions/{id}/revoke",
    "summary": "Revoke an assumed session",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "create-access-keys",
    "method": "POST",
    "path": "/api/v1/iam/access-keys",
    "summary": "Create an access key",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "principalType",
      "kind": "string",
      "required": true,
      "choices": [
       "user",
       "service_account"
      ]
     },
     {
      "name": "principalId",
      "kind": "string",
      "required": true
     },
     {
      "name": "label",
      "kind": "string",
      "required": false
     },
     {
      "name": "expiresAt",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "create-groups",
    "method": "POST",
    "path": "/api/v1/iam/groups",
    "summary": "Create a group",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": true
     },
     {
      "name": "description",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "create-groups-members",
    "method": "POST",
    "path": "/api/v1/iam/groups/{id}/members",
    "summary": "Members a group",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "userId",
      "kind": "string",
      "required": true
     }
    ]
   },
   {
    "name": "create-identity-providers",
    "method": "POST",
    "path": "/api/v1/iam/identity-providers",
    "summary": "Create an identity provider",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": true
     },
     {
      "name": "type",
      "kind": "string",
      "required": true,
      "choices": [
       "saml",
       "oidc"
      ]
     },
     {
      "name": "metadata",
      "kind": "json",
      "required": false
     }
    ]
   },
   {
    "name": "create-invites",
    "method": "POST",
    "path": "/api/v1/iam/invites",
    "summary": "Create an invite",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "email",
      "kind": "string",
      "required": true
     },
     {
      "name": "role",
      "kind": "string",
      "required": false,
      "choices": [
       "owner",
       "admin",
       "member"
      ]
     }
    ]
   },
   {
    "name": "create-policies",
    "method": "POST",
    "path": "/api/v1/iam/policies",
    "summary": "Create a policy",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": true
     },
     {
      "name": "description",
      "kind": "string",
      "required": false
     },
     {
      "name": "document",
      "kind": "json",
      "required": true
     }
    ]
   },
   {
    "name": "create-policy-attachments",
    "method": "POST",
    "path": "/api/v1/iam/policy-attachments",
    "summary": "Create a policy attachment",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "policyId",
      "kind": "string",
      "required": true
     },
     {
      "name": "principalType",
      "kind": "string",
      "required": true,
      "choices": [
       "user",
       "group",
       "role",
       "service_account"
      ]
     },
     {
      "name": "principalId",
      "kind": "string",
      "required": true
     }
    ]
   },
   {
    "name": "create-roles",
    "method": "POST",
    "path": "/api/v1/iam/roles",
    "summary": "Create a role",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": true
     },
     {
      "name": "description",
      "kind": "string",
      "required": false
     },
     {
      "name": "trustPolicy",
      "kind": "json",
      "required": true
     },
     {
      "name": "maxSessionDurationSec",
      "kind": "number",
      "required": false
     }
    ]
   },
   {
    "name": "create-service-accounts",
    "method": "POST",
    "path": "/api/v1/iam/service-accounts",
    "summary": "Create a service account",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": true
     },
     {
      "name": "description",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "create-users",
    "method": "POST",
    "path": "/api/v1/iam/users",
    "summary": "Create an user",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "email",
      "kind": "string",
      "required": true
     },
     {
      "name": "name",
      "kind": "string",
      "required": false
     },
     {
      "name": "password",
      "kind": "string",
      "required": false
     },
     {
      "name": "role",
      "kind": "string",
      "required": false,
      "choices": [
       "owner",
       "admin",
       "member"
      ]
     },
     {
      "name": "emailVerified",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "sendInviteEmail",
      "kind": "boolean",
      "required": false
     }
    ]
   },
   {
    "name": "delete-access-keys",
    "method": "DELETE",
    "path": "/api/v1/iam/access-keys/{id}",
    "summary": "Delete an access key",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "delete-groups",
    "method": "DELETE",
    "path": "/api/v1/iam/groups/{id}",
    "summary": "Delete a group",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "delete-groups-members",
    "method": "DELETE",
    "path": "/api/v1/iam/groups/{id}/members/{userId}",
    "summary": "Delete a member",
    "pathParams": [
     "id",
     "userId"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "delete-identity-providers",
    "method": "DELETE",
    "path": "/api/v1/iam/identity-providers/{id}",
    "summary": "Delete an identity provider",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "delete-invites",
    "method": "DELETE",
    "path": "/api/v1/iam/invites/{id}",
    "summary": "Delete an invite",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "delete-policies",
    "method": "DELETE",
    "path": "/api/v1/iam/policies/{id}",
    "summary": "Delete a policy",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "delete-policy-attachments",
    "method": "DELETE",
    "path": "/api/v1/iam/policy-attachments/{id}",
    "summary": "Delete a policy attachment",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "delete-roles",
    "method": "DELETE",
    "path": "/api/v1/iam/roles/{id}",
    "summary": "Delete a role",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "delete-service-accounts",
    "method": "DELETE",
    "path": "/api/v1/iam/service-accounts/{id}",
    "summary": "Delete a service account",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "delete-users",
    "method": "DELETE",
    "path": "/api/v1/iam/users/{id}",
    "summary": "Delete an user",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "get-groups",
    "method": "GET",
    "path": "/api/v1/iam/groups/{id}",
    "summary": "Get a group",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null,
    "aliases": [
     "groups-2"
    ]
   },
   {
    "name": "get-policies",
    "method": "GET",
    "path": "/api/v1/iam/policies/{id}",
    "summary": "Get a policy",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null,
    "aliases": [
     "policies-2"
    ]
   },
   {
    "name": "get-roles",
    "method": "GET",
    "path": "/api/v1/iam/roles/{id}",
    "summary": "Get a role",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null,
    "aliases": [
     "roles-2"
    ]
   },
   {
    "name": "get-service-accounts",
    "method": "GET",
    "path": "/api/v1/iam/service-accounts/{id}",
    "summary": "Get a service account",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null,
    "aliases": [
     "service-accounts-2"
    ]
   },
   {
    "name": "groups",
    "method": "GET",
    "path": "/api/v1/iam/groups",
    "summary": "List groups",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "identity-providers",
    "method": "GET",
    "path": "/api/v1/iam/identity-providers",
    "summary": "List identity providers",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "invites",
    "method": "GET",
    "path": "/api/v1/iam/invites",
    "summary": "List invites",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "policies",
    "method": "GET",
    "path": "/api/v1/iam/policies",
    "summary": "List policies",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "policy-attachments",
    "method": "GET",
    "path": "/api/v1/iam/policy-attachments",
    "summary": "List policy attachments",
    "pathParams": [],
    "query": [
     {
      "name": "policyId",
      "kind": "string",
      "required": false
     },
     {
      "name": "principalType",
      "kind": "string",
      "required": false,
      "choices": [
       "user",
       "group",
       "role",
       "service_account"
      ]
     },
     {
      "name": "principalId",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "roles",
    "method": "GET",
    "path": "/api/v1/iam/roles",
    "summary": "List roles",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "service-accounts",
    "method": "GET",
    "path": "/api/v1/iam/service-accounts",
    "summary": "List service accounts",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "update-identity-providers",
    "method": "PATCH",
    "path": "/api/v1/iam/identity-providers/{id}",
    "summary": "Update an identity provider",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": false
     },
     {
      "name": "metadata",
      "kind": "json",
      "required": false
     }
    ]
   },
   {
    "name": "update-policies",
    "method": "PATCH",
    "path": "/api/v1/iam/policies/{id}",
    "summary": "Update a policy",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "description",
      "kind": "string",
      "required": false
     },
     {
      "name": "document",
      "kind": "json",
      "required": false
     }
    ]
   },
   {
    "name": "update-users",
    "method": "PATCH",
    "path": "/api/v1/iam/users/{id}",
    "summary": "Update an user",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "role",
      "kind": "string",
      "required": false,
      "choices": [
       "owner",
       "admin",
       "member"
      ]
     },
     {
      "name": "emailVerified",
      "kind": "boolean",
      "required": false
     }
    ]
   },
   {
    "name": "users",
    "method": "GET",
    "path": "/api/v1/iam/users",
    "summary": "List users",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "users-reset-password",
    "method": "POST",
    "path": "/api/v1/iam/users/{id}/reset-password",
    "summary": "Reset password an user",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "mfa",
  "routes": [
   {
    "name": "challenge",
    "method": "GET",
    "path": "/api/v1/mfa/challenge",
    "summary": "Read-only — lets the standalone /mfa page render the right input (authenticator vs. emailed code) regardless of which flow created the challenge.",
    "pathParams": [],
    "query": [
     {
      "name": "token",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "delete-devices",
    "method": "DELETE",
    "path": "/api/v1/mfa/devices/{id}",
    "summary": "Delete a device",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "devices",
    "method": "GET",
    "path": "/api/v1/mfa/devices",
    "summary": "List devices",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "enroll",
    "method": "POST",
    "path": "/api/v1/mfa/enroll",
    "summary": "Create an enroll",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "method",
      "kind": "string",
      "required": false,
      "choices": [
       "totp",
       "email"
      ]
     },
     {
      "name": "label",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "resend-code",
    "method": "POST",
    "path": "/api/v1/mfa/resend-code",
    "summary": "Create a resend code",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "mfaChallengeToken",
      "kind": "string",
      "required": true
     }
    ]
   },
   {
    "name": "resend-enrollment-code",
    "method": "POST",
    "path": "/api/v1/mfa/resend-enrollment-code",
    "summary": "Create a resend enrollment code",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "deviceId",
      "kind": "string",
      "required": true
     }
    ]
   },
   {
    "name": "verify-enrollment",
    "method": "POST",
    "path": "/api/v1/mfa/verify-enrollment",
    "summary": "Create a verify enrollment",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "deviceId",
      "kind": "string",
      "required": true
     },
     {
      "name": "code",
      "kind": "string",
      "required": false
     },
     {
      "name": "totpCode",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "verify-login",
    "method": "POST",
    "path": "/api/v1/mfa/verify-login",
    "summary": "Create a verify login",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "mfaChallengeToken",
      "kind": "string",
      "required": true
     },
     {
      "name": "code",
      "kind": "string",
      "required": true
     }
    ]
   }
  ]
 },
 {
  "area": "oidc",
  "routes": [
   {
    "name": "clients",
    "method": "GET",
    "path": "/api/v1/oidc/clients",
    "summary": "List clients",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "clients-rotate-secret",
    "method": "POST",
    "path": "/api/v1/oidc/clients/{id}/rotate-secret",
    "summary": "Rotate secret a client",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "create-clients",
    "method": "POST",
    "path": "/api/v1/oidc/clients",
    "summary": "Create a client",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": true
     },
     {
      "name": "redirectUris",
      "kind": "array",
      "required": false
     },
     {
      "name": "scopes",
      "kind": "array",
      "required": false
     },
     {
      "name": "public",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "logoUrl",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "delete-clients",
    "method": "DELETE",
    "path": "/api/v1/oidc/clients/{id}",
    "summary": "Delete a client",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "update-clients",
    "method": "PATCH",
    "path": "/api/v1/oidc/clients/{id}",
    "summary": "Update a client",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": false
     },
     {
      "name": "redirectUris",
      "kind": "array",
      "required": false
     },
     {
      "name": "scopes",
      "kind": "array",
      "required": false
     },
     {
      "name": "logoUrl",
      "kind": "string",
      "required": false
     }
    ]
   }
  ]
 },
 {
  "area": "ops",
  "routes": [
   {
    "name": "end-users",
    "method": "GET",
    "path": "/api/v1/ops/end-users",
    "summary": "Workspace-scoped directory of end-users — people who have consented to an OIDC client owned by the active workspace.",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "end-users-impersonate",
    "method": "POST",
    "path": "/api/v1/ops/end-users/{id}/impersonate",
    "summary": "Impersonate an end user",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "durationSeconds",
      "kind": "number",
      "required": false
     }
    ]
   },
   {
    "name": "end-users-revoke",
    "method": "POST",
    "path": "/api/v1/ops/end-users/{id}/revoke",
    "summary": "Revoke an end user",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "end-users-send-password-reset",
    "method": "POST",
    "path": "/api/v1/ops/end-users/{id}/send-password-reset",
    "summary": "Send password reset an end user",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "end-users-stop-impersonation",
    "method": "POST",
    "path": "/api/v1/ops/end-users/stop-impersonation",
    "summary": "Create a stop impersonation",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "end-users-verify-email",
    "method": "POST",
    "path": "/api/v1/ops/end-users/{id}/verify-email",
    "summary": "Verify email an end user",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "get-end-users",
    "method": "GET",
    "path": "/api/v1/ops/end-users/{id}",
    "summary": "Get an end user",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null,
    "aliases": [
     "end-users-2"
    ]
   }
  ]
 }
];

// A field whose flag would clash with this command's own options or the CLI's global ones
// is given as --field-<name>.
const RESERVED = new Set(['help', 'version', 'json', 'profile', 'api', 'on-behalf-of', 'color', 'no-color', 'body-json']);
const plain = (name: string): string => name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/_/g, '-').toLowerCase();
const flag = (name: string): string => (RESERVED.has(plain(name)) ? `field-${plain(name)}` : plain(name));
const camel = (name: string): string => flag(name).replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());

function value(field: Field, raw: string): unknown {
  if (field.kind === 'number') {
    const n = Number(raw);
    if (Number.isNaN(n)) throw new Error(`--${flag(field.name)} must be a number`);
    return n;
  }
  if (field.kind === 'boolean') return raw === '' || raw === 'true' || raw === '1' || raw === 'yes';
  if (field.kind === 'array') return raw.trim().startsWith('[') ? JSON.parse(raw) : raw.split(',').map((x) => x.trim()).filter(Boolean);
  if (field.kind === 'json') return JSON.parse(raw);
  if (field.choices && !field.choices.includes(raw)) throw new Error(`--${flag(field.name)} must be one of: ${field.choices.join(', ')}`);
  return raw;
}

export function buildApiCommand(): Command {
  const api = new Command('api').description('Every route of the API, one command each (generated from the API spec)');
  for (const { area, routes } of API_ROUTES) {
    const group = new Command(area).description(`${area} routes`);
    for (const route of routes) {
      for (const name of [route.name, ...(route.aliases ?? [])]) {
      const cmd = new Command(name).description(`${route.summary} (${route.method} ${route.path})`);
      for (const p of route.pathParams) cmd.argument(`<${p}>`);
      const fields = [...route.query, ...(route.body ?? [])];
      for (const f of fields) {
        const hint = f.choices ? ` (${f.choices.join('|')})` : f.kind === 'json' || f.kind === 'array' ? ` (${f.kind})` : '';
        cmd.option(f.kind === 'boolean' ? `--${flag(f.name)} [value]` : `--${flag(f.name)} <value>`, `${f.required ? 'required' : 'optional'}${hint}`);
      }
      if (route.body) cmd.option('--body-json <json>', 'the whole body as JSON (fields given as flags override it)');
      cmd.action(async (...parts: unknown[]) => {
        const command = parts[parts.length - 1] as Command;
        const opts = command.opts() as Record<string, string | boolean | undefined>;
        try {
        let path = route.path;
        route.pathParams.forEach((p, i) => { path = path.replace(`{${p}}`, encodeURIComponent(String(parts[i]))); });
        const query: Record<string, unknown> = {};
        for (const f of route.query) {
          const raw = opts[camel(f.name)];
          if (raw !== undefined) query[f.name] = value(f, raw === true ? '' : String(raw));
        }
        let body: Record<string, unknown> | undefined;
        if (route.body) {
          body = opts.bodyJson ? (JSON.parse(String(opts.bodyJson)) as Record<string, unknown>) : {};
          for (const f of route.body) {
            const raw = opts[camel(f.name)];
            if (raw !== undefined) body[f.name] = value(f, raw === true ? '' : String(raw));
          }
          const missing = route.body.filter((f) => f.required && body![f.name] === undefined).map((f) => `--${flag(f.name)}`);
          if (missing.length) throw new Error(`missing ${missing.join(', ')}`);
        }
        await callRoute(command, route.method, path, query, body);
        } catch (err) {
          await failRoute(command, err);
        }
      });
      group.addCommand(cmd, { hidden: name !== route.name });
      }
    }
    api.addCommand(group);
  }
  return api;
}
